apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.9.1
    releaseName: longhorn
    namespace: longhorn-system

resources:
  - ssd-storageclass.yaml
  - ssd-storageclass-multi.yaml
  - longhorn-ingress.yaml
  - longhorn-secret.yaml