apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgBQtnhwMUQmks8ZCS5i4UVA11I/fFvVPWDNK91BDWd2gHnH0+av44xtmM8zfsIw/2FL5/fkvKA5COOweP7iVA4sR0YyxqHUbiREdU6I67Tkqx5VXAe5T2Z2rCIwzlQlZS6UIrxBQdfPDpUvqu7idKKSyvs30MwOxD/BRSjvzI0ABAQFd/Hgn0Zm0mtiTzIjGaPrAI+sSZm4sEzKx4tZfZMS5P8SQk0PBFkcVtfQeM5/ekao16Si7/bQEkUA2NvGmkRmUl0fiaBYARAST+vKu4EWcYqu94tn/ghC7jiLI8E6gkKV0Ua21fPAX9UV4dCh/9EijJEHoYtk6+7WDzkjn1i6AlJtVek2NVQ/vil24L8qvuPRzc2JYKF0E0+h0y8oIL/ogTr+lkeE/oFPJNJ7tTgnNcVidSatGEgvjQXLoBh9guNakI3dCj/wJ3FcI82ouoCZakyBHEJv0x0SXnofbcnPNX8Ab34yPgUnnmMxIGsCU6psXH9Lugpv6OiQdJOkIQbQ6lQVuCX0pMvMpnFECuS2ddPrPUQQ/w6xSA8sJuhcjsorM+Hw7MnViNEyIoz24lj0xxDy6BX+/KbPsvfWK/DPVMEW8hp6KViSC8x8b3cLQ7XOm7loiiJGVyfugp/3ayAdza/KMi0fNyxXVIarXklCWEXOpe1QtOgGnjsTKQbgg/4qAvMKogEIGuh992RHx3etiJYmpb1JyKPdM/v2s25RLYqQQjMfdFpzaqoHpy8E8/RfzqZOjzNU4oRdayPJXRg=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system
    type: Opague
