apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: http-gateway
  namespace: default
spec:
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: home.jarvis-home.dev
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: http-gateway-cert
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    hostname: code.jarvis-home.dev
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: http-gateway-cert
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    hostname: longhorn.jarvis-home.dev
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: http-gateway-cert
      mode: Terminate