{{- range .Values.projects }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind:  AppProject
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .description }}
  sourceRepos:
  - {{ $config.spec.source.repoURL }}
  {{- if $config.spec.source.additionalRepos }}
  {{- range $config.spec.source.additionalRepos }}
  - {{ . }}
  {{- end }}
  {{- end }}
  destinations:
    - namespace: '*'
      server: {{ $config.spec.destination.server | quote }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
{{ end -}}