apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-test
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    targetRevision: 4.12.3
    repoURL: kubernetes.github.io/ingress-nginx
    helm:
      valuesObject:
        controller:
          hostPort:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default