apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-config-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
