apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-logs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
