apiVersion: v1
kind: Service
metadata:
  labels:
    app: technitium
  name: technitium-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 5380
      protocol: TCP
      targetPort: web
  selector:
    app: technitium
