apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tailscale-oauth-secret
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./operator-oauth.yaml
